In [1]:
import numpy as np
import scipy.linalg as la
import time
import bezout_2 as bz

#TEX_DIR = '/home/jp/Documents/Bezout/bezout/tex/txt'
TEX_DIR = '../tex/txt'

deg = [1]*5

with open(TEX_DIR+'/deg.txt', 'w') as f:
    f.write(str(deg))
    
t = 4
m = 16000
n = len(deg)

Field = QQ
R = PolynomialRing(Field, 'x', n)
x = R.gens()
xx = [x[0]**0] + list(x)

fshape = [d+1 for d in deg]
dx = [(i+1)*deg[i] for i in range(n)]
dy = [(n-i)*deg[i] for i in range(n)]
fn, Dx, Dy = factorial(n), prod(dx), prod(dy)
with open(TEX_DIR+'/Dx.txt', 'w') as f:
    f.write("{0:d}".format(Dx))


P = [bz.rand_poly(n-1, m, deg, t, x) for i in range(n)] + xx
#P = load('P.sobj')

save(P, 'P')
bz.P2txt(n, deg, P, TEX_DIR)
F = [bz.poly2prism(fshape, p) for p in P]

TEX_DIR

t = time.clock()
Gx, Gy, Hx, Hy = bz._GH(n, fn, deg, dx, dy)
H, K = bz._HK(n, Hx, Hy)
J = bz._J(Dx, Dy, F, n, fshape, dx, dy, Gx, Gy)
C = bz._C(n, Dx, Dy, J)
B = bz._B(n, Dx, Dy, H, K, C)

construction_B_time = time.clock() - t
with open(TEX_DIR+'/construction_B_time.txt', 'w') as f:
    f.write("{0:.4f}".format(construction_B_time))

#B = bz.block_triang(n, Dx, Dy, dx, dy, deg, B)
BB = []
for k in range(n+1):
        Bk = matrix(Field, B[k])
        BB.append(Bk[:, :])
bz.bz2txt(n, TEX_DIR, BB)

"""
computing rank of B0
"""
t = time.clock()
r0 = rank(BB[0])
rank_B0_time = time.clock() - t

with open(TEX_DIR+'/rank_B0.txt', 'w') as f:
    f.write("{0:d}".format(r0))
with open(TEX_DIR+'/rank_B0_time.txt', 'w') as f:
    f.write("{0:.4f}".format(rank_B0_time))
print("sage_rank = {0:d}".format(r0))

bb = []
for k in range(n+1):
    bb.append(np.array(BB[k], dtype=float))

b0 = bb[0]
numpy_rank = np.linalg.matrix_rank(b0)
print("numpy_rank = {0:d}".format(numpy_rank))

sage_rank = 59
numpy_rank = 59


In [2]:
t = time.clock()
GB, grobner_dim = bz.compute_grobner(R, P, n)
print grobner_dim
grobner_time = time.clock() - t
bz.gb2txt(TEX_DIR, GB)

with open(TEX_DIR+'/grobner_dim.txt', 'w') as f:
    f.write("{0}".format(grobner_dim))

with open(TEX_DIR+'/grobner_time.txt', 'w') as f:
    f.write("{0:.4f}".format(grobner_time))

53


In [3]:
B0Y = BB[0]
Y = bz.find_Y(BB, B0Y, Field, n)

BBt = []
for k in range(n+1):
    BBt.append(BB[k].transpose())
B0Yt = B0Y.transpose()
X = bz.find_Y(BBt, B0Yt, Field, n)

print "-"*10
Y_ortho = Y.right_kernel_matrix()
bb0y = BB[0]*Y_ortho.transpose()
print rank(bb0y)
X_ortho = X.right_kernel_matrix()
xbb0 = X_ortho*BB[0]
print rank(xbb0)
xbb0y = X_ortho*BB[0]*Y_ortho.transpose()
print rank(xbb0y)


120
145
149
120
141
150
----------
53
53
53


In [5]:
XBBY = []
for k in range(n+1):
    XBBY.append(X_ortho*BB[k]*Y_ortho.transpose())
bezout_exact_dim = rank(XBBY[0])
#f.write("bezout_exact_dim = {0:d}\n".format(bezout_exact_dim))
print("bezout_exact_dim = {0:d}".format(bezout_exact_dim))

bezout_exact_dim = 53


In [6]:
K_ortho = XBBY[0].kernel().basis_matrix().right_kernel_matrix()
N_ortho = XBBY[0].right_kernel_matrix().right_kernel_matrix()
#N_ortho = N.kernel().basis_matrix().transpose()

KBBN = []
for k in range(n+1):
    KBBN.append(K_ortho*XBBY[k]*N_ortho.transpose())

In [7]:
Field = GF(next_prime(200))

BBf = []
for k in range(n+1):
        Bk = matrix(Field, KBBN[k])
        BBf.append(Bk[:, :])
        
if rank(BBf[0]) == bezout_exact_dim:
    XX = []
    for k in range(n):
        xx = BBf[0].solve_right(BBf[k+1])
        XX.append(xx)
    Pf = [bz.P2field(p, Field) for p in P]
    test_XX = [bz.X2p(XX, Field, p) for p in Pf[:n]]
    #f.write("test_XX = {0:s}".format(test_XX))
    print("test_XX = {0:s}".format(test_XX))
else:
        print "rank deficiency !"

test_XX = [(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)]


In [8]:
bb = []
for k in range(n+1):
    bb.append(np.array(KBBN[k], dtype=float))
roots = bz.BB2roots(bb)
test_roots = bz.roots_test(P, x, roots)
test_roots

array([  7.88223825e-11,   3.87765845e-11,   1.05454100e-11,
         6.48828356e-10,   5.93194324e-10,   3.75997647e-10,
         1.50976544e-11,   8.17167919e-10,   8.13929840e-10,
         7.24223112e-12,   6.32604991e-12,   8.00950145e-14,
         2.45982080e-13,   2.33623555e-12,   3.66202430e-12,
         1.64460195e-11,   3.31880837e-12,   4.50589211e-12,
         9.75710400e-12,   8.13555630e-12,   5.86364884e-12,
         1.09101028e-11,   1.43023604e-11,   3.55038144e-13,
         3.37106795e-13,   5.07776460e-12,   1.27693301e-12,
         8.83904122e-12,   3.06568212e-12,   2.60417018e-12,
         2.22966065e-12,   8.83700804e-12,   2.50721173e-12,
         3.17693189e-12,   1.22000175e-11,   8.66372145e-11,
         5.62544794e-11,   1.35224793e-11,   3.56813072e-11,
         2.07296334e-12,   2.66884163e-12,   2.27420341e-12,
         4.33951720e-12,   2.70857862e-12,   1.94161311e-12,
         2.55696868e-12,   8.04295506e-12,   3.23091380e-12,
         2.15281855e-12,

In [9]:
hist, bin_edges = np.histogram(np.log10(test_roots), bins='scott')
hist, bin_edges

(array([ 4,  1, 24, 14,  5,  5]),
 array([-13.09639452, -12.42827688, -11.76015924, -11.0920416 ,
        -10.42392397,  -9.75580633,  -9.08768869]))